apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-xpog
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lxoo-tenant/rhtap-demo-app/hacbs-test-project-xpog@sha256:ca043204dbc6862a415fb0d651969ee8a25e7d6d344986724487295259d76da4
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
